### ISSUE TITLE
An error is reported after clicking the ‘Get networks’ button

### ISSUE THREAD

**Issue by chuanlingZhao** [LokieVikky/wifi_scan_desktop#1]
![image](https://user-images.githubusercontent.com/85494339/236616441-a81cfe5f-dd02-429a-8042-d7b09f03953b.png)

An error is reported after clicking the ‘Get networks’ button

**Comment by LokieVikky** [comment]
Could you please share the stack trace

**Comment by chuanlingZhao** [comment]
Now it can run again, only occasionally reporting this error. Previously, an error was reported when an example was directly referenced after downloading the dependency, without any modifications.
